### PR TITLE
use webpack capabilities from vizlab 0.3.7

### PR DESCRIPTION
**Pull request by lindsaycarr**
This needs a new version of vizlab, so don't merge until that is 👍 https://github.com/USGS-VIZLAB/vizlab/pull/385. ~But, it makes all of the webpack magic happen behind-the-scenes (files are saved to target). Not yet sure how this might do on Jenkins.~ This runs webpacker() during vizmake() which bundles up the js files (and anything else specified) based on how the `webpack.config.js` is setup. It should stick them straight in `target/[something]`

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Not that I actually need this to build locally right now (except to explore webpack better), but here's what I got after running vizmake() some more:
```r
[ BUILD ] vizlab/remake/scripts/svg_state_map.R |  prepSources(outfile = "vizlab/remake/scripts/svg_...
[ BUILD ] cache/state_boundaries.svg            |  publish("svg_state_map")
Error: 'cache/state_boundaries.svg' does not exist in current working directory ('D:/APAData/GitHub/DS Vizzies/gage-conditions').
In addition: Warning messages:
1: In checkVizPackages() :
  these packages are newer than required: vizlab (need 0.3.6, have 0.3.7)
2: running command 'npm list webpack' had status 1 
3: running command 'npm list webpack-cli' had status 1 
4: running command 'npm list d3' had status 1 
5: package ‘tidyr’ was built under R version 3.4.4 
6: package ‘bindrcpp’ was built under R version 3.4.4 
7: Unknown variables: `p90_va` 
```

**Comment by jread-usgs** [comment]
I think those were the errors I got before I had `webpack` installed?

**Comment by aappling-usgs** [comment]
That may have been a correlation there, but I'm pretty sure this problem is independent of webpack. For one thing, I do have webpack installed. For another, the traceback is R all the way:
```r
> traceback()
26: stop(e)
25: h(simpleError(msg, call))
24: .handleSimpleError(function (e) 
    {
        restore(target$name, path)
        stop(e)
    }, "'cache/state_boundaries.svg' does not exist in current working directory ('D:/APAData/GitHub/DS Vizzies/gage-conditions').", 
        quote(NULL))
23: stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
        getwd(), "')"), ".", call. = FALSE)
22: check_path(path)
21: path_to_connection(x)
20: read_xml.character(viz[["location"]])
19: xml2::read_xml(viz[["location"]]) at inline_svg.R#2
18: publish.inline_svg(viz) at publish.R#8
17: publish(viz) at publish.R#16
16: publish.character("svg_state_map") at publish.R#8
15: publish("svg_state_map")
14: eval(target$command, envir)
13: eval(target$command, envir)
12: withCallingHandlers(eval(target$command, envir), message = function(e) if (quiet) invokeRestart("muffleMessage"))
11: target_run(target, store, quiet)
10: withCallingHandlers(target_run(target, store, quiet), error = function(e) {
        restore(target$name, path)
        stop(e)
    })
9: target_build(target, obj$store, obj$verbose$quiet_target)
8: remake_update2(obj, i, check = check, return_target = is_last)
7: FUN(X[[i]], ...)
6: lapply(plan, function(i) {
       is_last <- i == last_target_name
       remake_update2(obj, i, check = check, return_target = is_last)
   })
5: remake_update1(obj, plan, last_target_name, check = check)
4: remake_make1(obj, target_names, ...)
3: remake_make(obj, target_names)
2: remake::make(target_names = target_names, ..., remake_file = "remake.yaml") at vizmake.R#59
1: vizmake()
```
I'm thinking the issue is that cache/state_boundaries.svg doesn't get created in the main viz.yaml; it only gets published, and `publish.inline_svg` creates a character string but not a file.
```r
publish.inline_svg <- function(viz) {
  svg <- xml2::read_xml(viz[["location"]])
  xml_string <- xml2::as_xml_document(svg)
  
  return(as.character(xml_string))
}
```

I had assumed that as in previous vizzies, the map_preprocess.yml file was something that only one person needed to run, and that the results would get pushed to S3 or SB and then re-fetched in the main viz.yaml. Looks like that's not how y'all are doing it here.

Given that map_preprocess.yml is required running on each computer, do you really need/want it to be in a separate yml file? Maybe it should be part of viz.yaml so that dependencies on it can be captured.

**Comment by aappling-usgs** [comment]
My next step for local debugging was to remake map_preprocess.yml. which stopped on the same file. Maybe that's coincidence, or maybe you actually DO have a dependency link from viz.yaml to map_preprocess.yml that I haven't spotted yet. 

Either way, now I think the problem is indeed my system configuration, because
```
> remake::make(remake_file='map_preprocess.yml')
[  LOAD ] 
[  READ ]                                       |  # loading sources
<  MAKE > map_preprocess
[ BUILD ] display_proj                          |  display_proj <- CRS("+proj=laea +lat_0=45 +lon_0=...
[  READ ]                                       |  # loading packages
[ BUILD ] svg_x                                 |  svg_x <- c(960)
[ BUILD ] svg_y                                 |  svg_y <- c(600)
[ BUILD ] cache/pre_state_boundaries_census.zip |  fetch_url("cache/pre_state_boundaries_census.zip"...
[ BUILD ] state_boundaries_census_sp            |  state_boundaries_census_sp <- read_shp_zip("cache...
[ BUILD ] site_locations_sp                     |  site_locations_sp <- readRDS("cache/site_location...
[ BUILD ] site_locations_albers_sp              |  site_locations_albers_sp <- spTransform(site_loca...
[ BUILD ] state_boundaries_albers_sp            |  state_boundaries_albers_sp <- spTransform(state_b...
[ BUILD ] state_boundaries_mutated_sp           |  state_boundaries_mutated_sp <- mutate_sp_coords(s...
[ BUILD ] site_locations_mutated_sp             |  site_locations_mutated_sp <- mutate_sp_coords(sit...
[ BUILD ] state_boundaries_scaled_sp            |  state_boundaries_scaled_sp <- scale_fit_sp_coords...
[ BUILD ] site_locatations_scaled_sp            |  site_locatations_scaled_sp <- scale_fit_sp_coords...
[ BUILD ] cache/state_boundaries_scaled.geojson |  geojson_write(state_boundaries_scaled_sp, file = ...
Success! File is at cache/state_boundaries_scaled.geojson
[ BUILD ] cache/site_locations_scaled.geojson   |  geojson_write(site_locatations_scaled_sp, file = ...
Success! File is at cache/site_locations_scaled.geojson
[ BUILD ] cache/state_boundaries.svg            |  geo2svg("cache/state_boundaries_scaled.geojson", ...
Error in target_run(target, store, quiet) : 
  command for cache/state_boundaries.svg did not create file
In addition: Warning messages:
1: package ‘rgdal’ was built under R version 3.4.4 
2: package ‘geojsonio’ was built under R version 3.4.4 
3: running command 'geo2svg -w 960 -h 600 < cache/state_boundaries_scaled.geojson > cache/state_boundaries.svg' had status 127 
```
and
```
> system('which geo2svg')
/usr/bin/which: no geo2svg in (/c/Rtools/bin:{rest of PATH...})
Warning message:
running command 'which geo2svg' had status 1 
```

**Comment by lindsaycarr** [comment]
Yes, we don't have anything stored on SB or S3 right now, so everyone needs to run the preprocess. We had a short discussion about merging map_preprocess.yaml into the viz.yaml here: https://github.com/USGS-VIZLAB/gage-conditions/pull/12#issuecomment-401068140

**Pull request merged**
