### PR TITLE
process shifted/scaled states+PR+VI

### PR DESCRIPTION
**Pull request by jread-usgs**
For #4 

This is the first part of this tasks, which processes the spatial data to ready it for geojson/topojson/svg. 
Later processing for topoquantize and toposimplify will be included here too, but I wanted to get a PR up early to make sure I wasn't going in the wrong direction on this one. 

We'll also not want to lose sight of needing to transform/preprocess the gage locations in the same way so the land in the right spots on the map.

### CODE REVIEW

**Comment by jread-usgs** [comment]
```r
d = remake::make('state_boundaries_scaled_sp', remake_file = 'map_preprocess.yml')
```
generates
image


From here, we'll write to `geojson` and start the commandline processing.

**Comment by lindsaycarr** [comment]
Thinking big picture here, I'm wondering if this code should live in vizlab as functions with an additional functions for creating the map of the US, rather than a separate make workflow? Then, in this repo (and future repos), we could have a fetch step that gets the right spatial data and caches and then a process step that calls these vizlab process functions. We could have a similar process step for handling the site location data?

**Comment by jread-usgs** [comment]
I'm not sure. My initial reaction is that this isn't yet mature enough to include in vizlab, and we'll want to iterate on how well this works in projects. From the experience of working on water-use-15, for example, it seems we'll want to have access to how the states are scaled and shifted for different types of products (e.g., some tweets and thumbnails are more "landscape" others are more square, and I adjusted the scales/shifts for those aspect ratios and appreciated having the control to do so). but I do see the value of having more map templates available to vizlab projects.

**Comment by jread-usgs** [comment]
I will ask Blodgett to do a review after I include toposimple/quantize -> SVG

**Pull request merged**
